const menu = [{
  menuId: 1,
  catererId: 1,
  meals: [{
    mealId: 1,
    title: 'Chicken Sandwich',
    desc: 'Chicken, Vegetables, Potato, Bread, Lettuce',
    price: 1500,
    img: 'images.com/img1.jpeg',
  },
  {
    mealId: 2,
    title: 'Terrkulture Onion and Fish in basket',
    desc: 'Croaker Fish, Onion, Potato',
    price: 1200,
    img: 'images.com/img2.jpeg',
  },
  {
    mealId: 3,
    title: 'Boiled Sweet Potato',
    desc: 'Yam, Snail, Pepper, Onion, Spice',
    price: 2000,
    img: 'images.com/img3.jpeg',
  }],
  date: '04/05/2018',
},
{
  menuId: 2,
  catererId: 1,
  meals: [{
    mealId: 2,
    title: 'Terrkulture Onion and Fish in basket',
    desc: 'Croaker Fish, Onion, Potato',
    price: 1200,
    img: 'images.com/img2.jpeg',
  },
  {
    mealId: 3,
    title: 'Boiled Sweet Potato',
    desc: 'Yam, Snail, Pepper, Onion, Spice',
    price: 2000,
    img: 'images.com/img3.jpeg',
  },
  {
    mealId: 4,
    title: 'Omalet and Dodo',
    desc: 'Eggs, Plantain, Pepper, Spring Onion ',
    price: 1200,
    img: 'images.com/img4.jpeg',
  }],
  date: '09/05/2018',
},
{
  menuId: 3,
  catererId: 3,
  meals: [{
    mealId: 3,
    title: 'Boiled Sweet Potato',
    desc: 'Yam, Snail, Pepper, Onion, Spice',
    price: 2000,
    img: 'images.com/img3.jpeg',
  },
  {
    mealId: 4,
    title: 'Omalet and Dodo',
    desc: 'Eggs, Plantain, Pepper, Spring Onion ',
    price: 1200,
    img: 'images.com/img4.jpeg',
  }],
  date: '04/05/2018',
},
{
  menuId: 4,
  catererId: 3,
  meals: [{
    mealId: 1,
    title: 'Chicken Sandwich',
    desc: 'Chicken, Vegetables, Potato, Bread, Lettuce',
    price: 1500,
    img: 'images.com/img1.jpeg',
  },
  {
    mealId: 2,
    title: 'Terrkulture Onion and Fish in basket',
    desc: 'Croaker Fish, Onion, Potato',
    price: 1200,
    img: 'images.com/img2.jpeg',
  }],
  date: '05/05/2018',
}];

module.exports = menu;
